ls1intum/Apollon2

.husky/pre-commit
README.md
library/eslint.config.js
library/package.json
package-lock.json
package.json
standalone/server/eslint.config.js
standalone/server/package.json
standalone/webapp/eslint.config.mjs
standalone/webapp/package.json
standalone/webapp/src/main.tsx

This PR solves https://github.com/ls1intum/Apollon2/issues/41
Project static code quality is checked by eslint rules.
npm run lint is added to recommit husky hook, so that before committing rules will be checked by eslint.
A developer can also run ```npm run lint``` or ```npm run lint:fix``` from the root to check the linting status of the project anytime

feat: 41 create eslint configurations for library webapp and server

---

library/lib/nodes/TitleAndDescriptionNode.tsx
library/lib/nodes/classDiagram/Class.tsx
library/lib/nodes/classDiagram/Package.tsx
library/lib/nodes/wrappers/DefaultNodeWrapper.tsx
library/lib/styles/app.css
standalone/webapp/src/components/navbar/DesktopNavbar.tsx
standalone/webapp/src/components/navbar/MobileNavbar.tsx

Place handle position based on width and height of the component
https://github.com/user-attachments/assets/1ab76f37-325e-4ea2-9463-9cf9cd12cf42

Fix  handling styles and positions

---

library/package.json
package-lock.json
standalone/webapp/index.html
standalone/webapp/package.json
standalone/webapp/src/App.tsx
standalone/webapp/src/components/APButton.tsx
standalone/webapp/src/components/modals/NewDiagramFromTemplateModal.tsx
standalone/webapp/src/components/modals/NewDiagramModal.tsx
standalone/webapp/src/components/modals/ShareModal.tsx
standalone/webapp/src/components/navbar/DesktopNavbar.tsx
standalone/webapp/src/types/ModalTypes.ts
standalone/webapp/src/webapp.css
standalone/webapp/src/wrappers/ModalWrapper.tsx
standalone/webapp/vite.config.ts

This PR completes https://github.com/ls1intum/Apollon2/issues/60
https://github.com/user-attachments/assets/3d5aafac-2b0c-4c3c-827a-3509beb91aec

feat-60  add share modal modal

---

.github/workflows/deploy-prod.yml

fix: remove tag for proxy

---

.github/workflows/deploy-prod.yml

fix:add image tag

---

.github/workflows/deploy-prod.yml
docker/compose.proxy.yml

fix: remove caddy from workflow

---

.github/workflows/build-and-push.yml
docker/compose.webapp.yml

ci: update workflow build args

---

docker/compose.webapp.yml

fix: remove args

---

.github/workflows/build-and-push.yml
docker/compose.prod.yml
docker/compose.webapp.yml

No ticket, fix ws url in builds

fix: ws url in deployments

---

library/lib/components/Sidebar.tsx
library/lib/components/popovers/edgePopovers/EdgeEditPopover.tsx
library/lib/constants/dropElementConfig.tsx
library/lib/hooks/useConnect.ts

Bug fixes for
connection new edge selected
edit edge popover spacing
sidebar new element id for methods and attributes
1. ...

Fix  connection new edge selected, edit edge popover spacing, sidebar new element id for methods and attributes

---

library/package.json
package-lock.json
standalone/webapp/package.json

NO ticket 
Use react and react-dom as dependencies in the library

feat: use react and react-dom as dependencies in the library

---

library/lib/apollon-editor.tsx
library/lib/store/diagramStore.ts
standalone/webapp/src/pages/ApollonLocal.tsx
standalone/webapp/src/pages/ApollonPlayground.tsx
standalone/webapp/src/pages/ApollonWithConnection.tsx

Artemis integration needed 
Apollon library dispose function is renamed to destroy to align with Artemis side 
new functions "set Model, addOrUpdateAssessment" are added to the library

feat: add-set-model-and-addorUpdateAssessment

---

library/lib/components/Sidebar.tsx
library/lib/styles/app.css
library/lib/utils/exportUtils.ts
standalone/webapp/src/pages/ApollonPlayground.tsx
standalone/webapp/src/webapp.css

Svg element creation fixed with creating element with name space
1. Create diagram
2. Export as svg
3. Observe SVG

fix: svg element creation

---

library/lib/nodes/classDiagram/Class.tsx

chore: remove console.warns

---

.github/workflows/publish-library-minor.yaml
library/lib/hooks/useHandleDelete.ts

Fix  update publish library minor job name

---

library/lib/store/diagramStore.ts

This PR completes https://github.com/ls1intum/Apollon2/issues/217
1. Add nodes and resize
https://github.com/user-attachments/assets/9cbeafd0-8005-4aec-b049-d71d27e07dcb

fix: Node resizing to support left and top expansion

---

library/lib/nodes/activityDiagram/ActivityForkNode.tsx
library/lib/nodes/activityDiagram/ActivityForkNodeHorizontal.tsx
library/lib/nodes/classDiagram/Class.tsx
library/lib/nodes/wrappers/DefaultNodeWrapper.tsx
library/lib/styles/app.css
renovate.json

This PR completes https://github.com/ls1intum/Apollon2/issues/222
1. Create Class node
2. Try to resize it vertically and don't see any arrow icon
https://github.com/user-attachments/assets/e159f527-1020-4aac-bd58-fabe55a9905e

fix: resize endge cursor fix if node is not resizable

---

standalone/webapp/src/pages/ApollonWithConnection.tsx

This PR completes https://github.com/ls1intum/Apollon2/issues/264
1. Create a new diagram
2. Go to share and use givefeedback or see feedback or collaboration
3. Share it
4. Observer canvas is rendered and you can create diagram elements
<table>
<tr>
<td>
Before
</td>
<td>
After
</td>
</tr>
<tr>
<td>
https://github.com/user-attachments/assets/83cb5630-3643-41ee-a345-c5fddda7a611
</td>
<td>
https://github.com/user-attachments/assets/902a749a-26f0-4f39-a475-7bb8f073c31a
</td>
</tr>
</table

fix: render responsive library in standalone apollon with connection

---

library/lib/components/popovers/PopoverManager.tsx
library/lib/components/popovers/edgePopovers/ReachabilityGraphEdgeEditPopover.tsx
library/lib/edges/edgeTypes/ReachabilityGraphArc.tsx
library/lib/edges/types.tsx
library/lib/utils/edgeUtils.ts

[This PR completes https://github.com/ls1intum/Apollon2/issues/xx](https://github.com/ls1intum/Apollon2/issues/280)
Create Reachability Graph Arc
1. Create Reachability Graph. 
2. Add edge, move nodes.
3. Try reconnection.
4. Try label.
5. Try midpoint customization.
https://github.com/user-attachments/assets/0072b2ce-e48e-4935-af65-31754ee786ec

feat: add reachability graph arc

---

library/lib/apollon-editor.tsx
library/lib/typings.ts
standalone/webapp/src/pages/ApollonWithConnection.tsx

Testing collaboration performance if the undo manager is creating lag

test: disable undo manager in colloboration

---

library/lib/utils/versionConverter.ts

feat: add color attributes for child fields

---

standalone/webapp/package.json
standalone/webapp/src/components/modals/AboutModal.tsx
standalone/webapp/src/constants/version.ts

chore: update webapp version
